name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Package
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest]

    permissions:
      contents: read 

    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js ️
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 

      - name: Install dependencies 
        run: pnpm install --frozen-lockfile

      - name: Build 
        run: pnpm run build 

      - name: Upload artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist 

  publish:
    needs: build
    name: Publish GitHub Packages
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest]

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js ️
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download artifacts 
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist 

      - name: Publish GitHub Packages 
        run: pnpm publish
        env:
          GITHUB_PACKAGES_NPM_PUBLISH_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
