name: publish package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8  # Specify the desired pnpm version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update package.json version  # Adapt for pnpm versioning strategy
        run: echo "Skipping version update on push event (adapt for pnpm)"

      - name: Publish package
        run: pnpm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
